update README setup, gitignore, starter code
learn-co-curriculum/python-p3v3-request-response-cycle pull request #1
Opened 2023-11-06 18:48 UTC by linda-seiter

2023-11-06 19:12 UTC, linda-seiter commented
moving lesson from phase 4

2023-11-16 23:26 UTC, AlveeM requested changes

2023-11-16 23:26 UTC, AlveeM commented on README.md
> +## [response]: https://flask.palletsprojects.com/en/2.3.x/api/#response-objects
Remove heading.

2023-11-17 13:14 UTC, linda-seiter commented on README.md
> +## [response]: https://flask.palletsprojects.com/en/2.3.x/api/#response-objects
fixed

2023-11-17 14:33 UTC, merged